image: node:16.5.0

stages:
  - build

build:
  stage: build
  script:
    - unset $(compgen -v | grep "CI")
    - env
    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
    - apt-get update
    - apt-get install -y jq git-lfs
    - git clone https://github.com/signalapp/Signal-Desktop.git
    - cd Signal-Desktop
    - git checkout $(git describe --tags $(git rev-list --tags --max-count=100) | grep -v beta | head -n 1)
    - cat package.json | jq '.build.linux += {target:["AppImage"]}' > with_appimage_package.json
    - mv with_appimage_package.json package.json
    - yarn install
    - yarn build-release
    - ls -la ./release
    - pwd

  artifacts:
    paths:
      - ./Signal-Desktop/release/*.AppImage
    expire_in: 1 week
        
