image: registry.mdedonno.ch/infra/base

stages:
  - build

build:
  stage: build
  script:
    - unset $(compgen -v | grep "CI")
    - env
    - apt-get update
    - apt-get install -y git python python-dev build-essential curl wget jq tree
    - cd /tmp
    - wget https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    - bash ./install.sh
    - source ~/.profile
    - git clone https://github.com/signalapp/Signal-Desktop.git
    - cd Signal-Desktop
    - git checkout master
    - nvm install 12.13.0
    - nvm use
    - npm install --global yarn
    - yarn install --frozen-lockfile
    - yarn grunt
    - cat package.json | jq '.build.linux += {target:["deb","AppImage"]}' > with_appimage_package.json
    - mv with_appimage_package.json package.json
    - yarn generate
    - yarn build-release
    - ls -la
    - ls -la ./release
    - pwd

  artifacts:
    paths:
      - /tmp/Signal-Desktop/release
        
