image: node:12.13.0

stages:
  - build

build:
  stage: build
  script:
    - unset $(compgen -v | grep "CI")
    - env
    - git clone --depth=1 --branch=master https://github.com/signalapp/Signal-Desktop.git
    - cd Signal-Desktop
    - cat package.json | jq '.build.linux += {target:["deb","AppImage"]}' > with_appimage_package.json
    - mv with_appimage_package.json package.json
    - yarn install
    - yarn build-release
    - ls -la ./release
    - pwd

  artifacts:
    paths:
      - ./Signal-Desktop/release/*.AppImage
        
