image: registry.mdedonno.ch/infra/base

stages:
  - build

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y git python python-dev build-essential curl
    - cd /tmp
    - wget https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    - bash ./install.sh
    - source ~/.profile
    - git clone https://github.com/signalapp/Signal-Desktop.git
    - cd Signal-Desktop
    - ls -la

